kubernetes-sigs/kube-storage-version-migrator

pkg/apis/migration/v1alpha1/types.go

KEP: https://github.com/kubernetes/community/blob/17248af3560a52b2c09ef667449a8a225e000416/keps/sig-api-machinery/0030-storage-migration.md
/assign @lavalamp @deads2k @yliaog

Add the API types described in the KEP

---

pkg/initializer/initializer.go

Adding the initializer object, which discovers migratable resources, and creates StorageVersionMigraion objects for each migratable resources.

Initializer Part II, adding the initializer

---

Makefile
cmd/initializer/Dockerfile
cmd/migrator/Dockerfile
manifests/initializer.yaml
manifests/migrator.yaml
manifests/namespace-rbac.yaml

Adding yamls to enable deploying the migrator from kubectl.

Run as k8s workloads

---

Makefile
manifests/namespace-rbac.yaml
test/e2e/test-cmd.sh

Add a simple case to the e2e test to actually exercise the migrator.

Run the migrator in the e2e test

---

README.md

Add links to the KEPs to the README

---

pkg/controller/helpers.go
pkg/controller/indexer.go
pkg/controller/indexer_test.go
pkg/controller/kubemigrator.go

* making the status indexer public
* adding an indexer that's based on the resource
The triggering controller needs both indexers.
I will move the indexer to its own package in a follow-up PR.
/assign @yliaog 
/sig api-machinery

Indexer refactor

---

pkg/apis/migration/v1alpha1/register.go
pkg/trigger/controller.go
pkg/trigger/discovery_handler.go
pkg/trigger/discovery_handler_test.go
pkg/trigger/migration_handler.go

Adding the triggering controller as described in [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/storage-migration-auto-trigger.md#storage-migration-triggering-controller).
I still need to add e2e tests. It's blocked by https://github.com/kubernetes/kubernetes/pull/72942.

Adding the triggering controller

---

test/e2e/crd.yaml
test/e2e/e2e_test.go
test/e2e/ginkgo-e2e.sh
test/e2e/test-cmd.sh
test/e2e/test-fully-automated.sh
test/e2e/tests/crd-migration.go
test/e2e/util/ginkgowrapper/wrapper.go
test/e2e/util/util.go

Adding e2e test checking the triggering controller working with the migrator

---

test/e2e/chaosmonkey/chaosmonkey.go
test/e2e/test-cmd.sh
test/e2e/test-fully-automated.sh
test/e2e/tests/chaos.go
test/e2e/tests/crd-migration.go
test/e2e/tests/setup.go

Adding a chaos test where the apiserver is restarted many times in a 10-minute window.
/assign @yliaog

Chaos testing

---

test/e2e/test-cmd.sh

#27 was merged accidentally. This one made the script more bullet-proof.
Original PR description.
The etcd server has enabled mTLS. Adding the necessary mTLS flags.
/assign @yliaog 
Unblock #27

Fixing test-cmd.sh.

---

pkg/apis/migration/v1alpha1/types.go

adding missing json tags

---

pkg/controller/kubemigrator.go
pkg/migrator/metrics/metrics.go

Sample metrics output: https://pastebin.com/TPdHLvCd
/assign @yliaog @logicalhan

Add metrics for migration status

---

pkg/migrator/metrics/metrics.go

see https://github.com/kubernetes-sigs/kube-storage-version-migrator/pull/32#pullrequestreview-250806881
/assign @yliaog @logicalhan

lower case metrics label name

---

test/e2e/tests/chaos.go

Making trigger controller and migrator controller randomly restarting in the chaos test.
/assign @yliaog

Making trigger controller and migrator controller randomly restarting in the chaos test

---

cmd/migrator/app/migrator.go
cmd/trigger/app/trigger.go

Allow passing in kubeconfig path

---

Makefile
manifests/initializer.yaml
manifests/migrator.yaml
manifests/namespace-rbac.yaml
manifests/trigger.yaml
pkg/initializer/initializer.go
pkg/trigger/controller.go
pkg/trigger/discovery_handler.go
test/e2e/test-cmd.sh
test/e2e/tests/crd-migration.go

Defaulting to kube-system.
/assign @yliaog

Make the namespace where the migration system run configurable,

---

manifests/crd.yaml
manifests/namespace-rbac.yaml
pkg/apis/migration/v1alpha1/types.go
pkg/clients/clientset/typed/migration/v1alpha1/fake/fake_migration_client.go
pkg/clients/clientset/typed/migration/v1alpha1/fake/fake_storageversionmigration.go
pkg/clients/clientset/typed/migration/v1alpha1/migration_client.go
pkg/clients/clientset/typed/migration/v1alpha1/storageversionmigration.go
pkg/clients/informer/migration/v1alpha1/interface.go
pkg/clients/informer/migration/v1alpha1/storageversionmigration.go
pkg/clients/lister/migration/v1alpha1/expansion_generated.go
pkg/clients/lister/migration/v1alpha1/storageversionmigration.go
pkg/controller/indexer.go
pkg/controller/kubemigrator.go
pkg/initializer/initializer.go
pkg/trigger/controller.go
pkg/trigger/discovery_handler.go
pkg/trigger/discovery_handler_test.go
pkg/trigger/migration_handler.go
test/e2e/tests/chaos.go
test/e2e/tests/crd-migration.go

Cluster scoped migration API

---

README.md
USER_GUIDE.md
manifests/kustomization.yaml

Add a user guide

---

cmd/initializer/initializer.go
cmd/migrator/migrator.go
cmd/trigger/trigger.go
pkg/controller/kubemigrator.go
pkg/initializer/discover.go
pkg/trigger/discovery_handler.go
pkg/trigger/migration_handler.go

imports: `k8s.io/klog/glog ==> k8s.io/klog`
code: `glog.* ==> klog.*`

move from glog to klog

---

pkg/controller/indexer_test.go

Fix the flakiness in `TestResourceIndexedInformer`.

Fix flaky test

---

test/e2e/tests/chaos.go
test/e2e/tests/crd-migration.go

e2e tests are no longer compiling correctly

tests/e2e: client calls missing ctx params

---

test/e2e/test-cmd.sh

In 1.19, the master node uses cri-o instead of docker as the container driver, so switch to crictl.
/assign @roycaihw

Switch to use crictl in e2e test

---

pkg/trigger/discovery_handler.go
test/e2e/test-cmd.sh

Log the group name as well to be more informative

---

Makefile
README.md

fixes https://github.com/kubernetes-sigs/kube-storage-version-migrator/issues/64
/cc @caesarxuchao

set default image build registry; update readme about the published images

---

cmd/migrator/app/migrator.go
cmd/trigger/app/trigger.go
manifests/migrator.yaml
manifests/trigger.yaml

Fixes https://github.com/kubernetes-sigs/kube-storage-version-migrator/issues/67. I manually tested in GKE. 
/assign @caesarxuchao

add healthz to migrator and trigger

---

cmd/initializer/app/initializer.go
manifests/storage_migration_crd.yaml
manifests/storage_state_crd.yaml
pkg/initializer/discover.go
pkg/initializer/discover_test.go
pkg/initializer/initializer.go
test/e2e/tests/chaos.go

apiextensions.k8s.io/v1beta1 is no longer available as of 1.22.
/assign @roycaihw

update usage of apiextension/v1beta1 to v1
